import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import MainLayoutSidebar from '@/components/layout/main/sidebar'

const sans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <div className="flex">
          <MainLayoutSidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
